id: P000754
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:41:16.477624
source_metadata:
  id: bdr:W1KG5396
  title: གཞོན་ནུ་ཟླ་མེད་ཀྱི་གཏམ་རྒྱུད་
  author: ''
  volumes:
    a3799ccb541e4a969c7f8f4140d7dbd5:
      image_group_id: I1KG5411
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
