id: P000754
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5396
  title: གཞོན་ནུ་ཟླ་མེད་ཀྱི་གཏམ་རྒྱུད་
  author: ''
  volumes:
    a3799ccb541e4a969c7f8f4140d7dbd5:
      image_group_id: I1KG5411
      title: ''
      volume_number: 1
      total_pages: 334
